# =======================================================================================================
# This is a script for generating Figure3: Splicing outlier detection
# #
# input:
#       1. Figure3.in.RData
#          Data generated by running Figure3_getdata.R
#
# output:
#       1. Figure3B.pdf, Figure3C.pdf, Figure3D.pdf,Figure3E.pdf
#       2. Figure3.out.RData
#          Store all data used and generated by running this script
#
# Note that the final figure was generated by using inkscape by combining figures from this script for visualization purposes
#
# =======================================================================================================



#!/bin/R

#Libraries
library(ggplot2)
library(dplyr)
library(cowplot)
library(RColorBrewer)
library(ggpubr)
library(ggbeeswarm)
rm(list=ls())


fsize=15
RD_theme=theme_classic()+
	theme(axis.text.x= element_text(size=fsize),
	axis.text.y= element_text(size=fsize), 
	axis.title = element_text(size = fsize), 
    legend.text = element_text(size = fsize-1), 
    legend.title = element_text(size = fsize), 
    axis.ticks = element_line(size = 0.1),
	strip.background=element_blank(),
	panel.grid.major=element_blank(),
	panel.grid.minor=element_blank(),
	axis.text=element_text(size=9),
	panel.border=element_blank()) 




# Master directory
dir = Sys.getenv('RARE_DIS_DIR')



#  Load input data
fig3b=read.table("Fig3b_data.txt",sep="\t", header=T)
fig3c=read.table("Fig3c_data.txt",sep="\t", header=T)
fig3d=read.table("Fig3d_data.txt",sep="\t", header=T)
fig3e=read.table("Fig3e_data.txt",sep="\t", header=T)
fig3f=read.table("Fig3f_data.txt",sep="\t", header=T)


#--- MAIN

# Figure 3b: 
fig3b_plot=ggplot(fig3b, aes(x=as.factor(variable), y=value+1))+
	geom_boxplot(color="black", fill="grey")+#fill="#028482")+
	#stat_summary(fun.y=mean, geom="point", size=2, color="#028482")+ 
	#stat_summary(fun.data=data_summary, geom="pointrange", color="black", size=1)+
	#scale_fill_brewer(palette="Paired",name="Affected status")+
	scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),labels = scales::trans_format("log10", scales::math_format(10^.x)))+
	labs(x="Z-score threshold", y="Number of genes with\nat least one outlier")+RD_theme #+theme(legend.position="bottom")







# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Figure 3C
col_splic_out=c( "#87907D"	,"#AAB6A2", 	"#666666")

fig3c_plot=ggplot(fig3c, aes(x=variable, y=value+1, fill=filter)) + 
geom_boxplot()+ 
scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),labels = scales::trans_format("log10", scales::math_format(10^.x)))+
scale_fill_manual(values=col_splic_out, name="Data filtered for\nsplicing outliers")+
scale_x_discrete(breaks=c("RV_number_MAF0", "RV_number_MAF0.1", "RV_number_MAF1"), labels=c("0", "0.1", "1"))+
labs(x="MAF (%)", y="Number of rare variants")+facet_grid(  . ~variant_data , scales="free_y")+RD_theme +theme(legend.position=c(0.4,0.9))



# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Figure 3 D
## Influence of filtering on splicing outlier results
# plot results
fig3d_plot=ggplot(fig3d, aes(x=variable, y=value, fill=variable) )+ 
	geom_boxplot(color="black", notch=F, show.legend = FALSE)+
	geom_point(size = 0, stroke = 0)+
	scale_fill_manual(values=rep("lightgrey", 8), breaks=c("prop_pLI","prop_HPO","prop_RV", "prop_RVpLI", "prop_CADD","prop_RVHPO", "prop_RVHPOCADD","prop_combined"),
		labels=c(expression("pLI " >="0.9"), "HPO match", expression("Rare variant within 20bp","1 + 3","3 + CADD score  " >= "10"), "2 + 3", "2 + 5", "1 + 2 + 3 + 5"), name="Filter")+
	scale_x_discrete(breaks=c("prop_pLI","prop_HPO","prop_RV", "prop_RVpLI", "prop_CADD","prop_RVHPO", "prop_RVHPOCADD","prop_combined"),
		labels=c("1", "2", "3","4","5", "6", "7", "8"))+
	labs(x="Filter", y="Proportion of outlier genes") + RD_theme +guides(fill = guide_legend(override.aes = list(size = 4,shape =c(49,50,51,52,53,54,55,56))))+theme(legend.position = c(0.8,0.8))
fig3d_plot

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

# Figure 3 E
custom_comparisons=list( c("outliers","outlier_RV_CADD_HPO_junc"))

fig3e_plot=ggboxplot(fig3e%>% filter(variable %in% c("outliers","outlier_RV_CADD_HPO_junc")), x = "variable", y = "value", color = "variable", palette =c("#C0C0C0", "#336699"), add = "jitter", shape = "variable")+
	#stat_compare_means(comparisons = custom_comparisons, label = "p.signif")+
	stat_compare_means(comparisons = custom_comparisons)+
	scale_x_discrete(labels= c( "Z-score >=2", "+ RV within 20bp junction\n+ HPO match"))+
	RD_theme+
	theme(legend.position="")+
	labs(x="Filter", y="Median number of rare variants per gene")

ggsave('Figure3E.pdf', RV_filters_plot,  path=paste(dir,"/analysis/manuscript/figures_revision/", sep=""), width=3, height=6)


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

# Figure 3 F


color = grDevices::colors()[grep('gr(a|e)y', grDevices::colors(), invert = T)]
mycol=sample(color, 75)

median.quartile <- function(x){
	out <- quantile(x, probs = c(0.25,0.5,0.75))
	names(out) <- c("ymin","y","ymax")
	return(out) 
}

ggplot(fig3f, aes(x = log10(value+1), y = filter, colour = sample)) +#geom_path(group=sample, colour="grey") + 
	stat_summary(fun.data="median.quartile",geom="pointrange", na.rm=T, color="black") + 
	#geom_quasirandom(groupOnX=FALSE) +
	theme(legend.position="")#+ 
	#scale_colour_manual(values=mycol) 
fig3f=data.frame(variable=fig3f$variable, value=unlist(fig3f$value),SAMPLE=unlist(fig3f$SAMPLE) )
fig3f_plot= ggplot(fig3f, aes(variable,value))+ 
 	geom_quasirandom(aes(y =value, x = variable, colour = SAMPLE))+
 	stat_summary(fun.data = median.quartile, geom = "pointrange",position=position_nudge(x=0.5,y=0))+
	coord_flip()+
	#geom_path(group=sample, colour="grey")+
 	theme(legend.position="")+
 	scale_colour_manual(values=mycol) +
 	labs(y="log10(Number of genes +1)",x="Filter")+
 	scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),labels = scales::trans_format("log10", scales::math_format(10^.x))) 



## Final plot was modified with Inkscape for aestetics purposes.


