# =======================================================================================================
# This is a script for generating Figure2D: Proportion of under-expression outlier genes remainingafter filters.
# #
# input:
#       1. Figure2D.in.RData
#          Data generated by running Figure2D_getdata.R
#
# output:
#       1. Figure2D.pdf
#       2. Figure2D.out.RData
#          Store all data used and generated by running this script
#
# Note that the final figure was generated by using inkscape by combining figures from this script for visualization purposes
#
# =======================================================================================================

#!/bin/R

# This scripts performs analyses for influence of differet filters on the number of expression outlier gene candidates for Figure 2
#Libraries
library(ggplot2)
library(cowplot)
library(corrplot)
library(RColorBrewer)


## FUNCTIONS

rm(list=ls())


# Master directory
dir = Sys.getenv('RARE_DIS_DIR')


#  Load input data
load(file = paste(dir,"/data/Figure2D.in.RData",sep=""))


fsize=15
RD_theme=theme_classic()+
	theme(axis.text.x= element_text(size=fsize),
	axis.text.y= element_text(size=fsize), 
	axis.title = element_text(size = fsize), 
    legend.text = element_text(size = fsize-1), 
    legend.title = element_text(size = fsize), 
    axis.ticks = element_line(size = 0.1),
	strip.background=element_blank(),
	panel.grid.major=element_blank(),
	panel.grid.minor=element_blank(),
	axis.text=element_text(size=9),
	panel.border=element_blank()) 



# plot results
filter_withsglt.exp.case.10kb.plot=ggplot(sample_exp_outlier_filter_withsgl_10kb_up.df.m.cases, aes(x=variable, y=value, fill=variable) )+ 
	geom_boxplot(color="black", notch=F, show.legend = FALSE)+
	geom_point(size = 0, stroke = 0)+
	scale_fill_manual(values=rep("lightgrey", 13), breaks=c("prop_pLI","prop_RIVER","prop_ASE", "prop_HPO","prop_RV", "prop_RV.pLI", "prop_CADD","prop_RV.RIVER","prop_RV.HPO", "prop_RV.ASE", "prop_RV.HPO.CADD","prop_RV.HPO.CADD.pLI","prop_RV.HPO.CADD.ASE"),
		labels=c(expression("pLI " >="0.9"), expression("RIVER " >= "0.85"), "ASE", "HPO match", expression("Rare variant within 10kb","1 + 5","5 + CADD score  " >= "10"), "2 + 5", "4 + 5", "3 + 5", "4 + 7", "1 + 2 + 5 + 7", "2 + 4 + 5 + 7"), name="Filter")+
	scale_x_discrete(breaks=c("prop_pLI","prop_RIVER","prop_ASE", "prop_HPO","prop_RV", "prop_RV.pLI", "prop_CADD","prop_RV.RIVER","prop_RV.HPO", "prop_RV.ASE", "prop_RV.HPO.CADD","prop_RV.HPO.CADD.pLI","prop_RV.HPO.CADD.ASE"),
		labels=c("1", "2", "3","4","5", "6", "7", "8", "9", "10", "11", "12", "13"))+
	labs(x="Filter", y="Proportion of outlier genes") + RD_theme +guides(fill = guide_legend(override.aes = list(size = 4,shape =c(49,50,51,52,53,54,55,56,57,58,59,60,61))))+theme(legend.position = c(0.8,0.7))

ggsave('Figure2D.pdf', filter_withsglt.exp.case.10kb.plot, path=paste(dir,"/analysis/manuscript/figures/", sep=""), width=6, height=6)


# Save data
save.image(file = paste(dir,"/data/Figure2D.out.RData",sep=""))
