#!/bin/R


# =======================================================================================================
# This is a script for generating Figure 1:  Using blood RNA-seq to study rare disease genes.
#
# Note that the final figure was generated by using inkscape by combining figures from this script for visualization purposes
#
# =======================================================================================================


#--- Libraries

library(cowplot)
library(ggplot2)
library(RColorBrewer)
library(ggpubr)
library(dplyr)


#--- Main
# Load Fig1a data
fig1a=read.table('Fig1a_data.txt', header=T)

# Load fig1b data
fig1b=read.table('Fig1b_data.txt', header=T)

#--- Figures
fsize=15
RD_theme=theme_classic()+
	theme(axis.text.x= element_text(size=fsize),
	axis.text.y= element_text(size=fsize), 
	axis.title = element_text(size = fsize), 
    legend.text = element_text(size = fsize-1), 
    legend.title = element_text(size = fsize), 
    axis.ticks = element_line(size = 0.1))


# Figure 1A
blank_theme <- theme_minimal()+
  theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  plot.title=element_text(size=fsize, face="bold"),axis.text.x= element_text(size=fsize),
	axis.text.y= element_text(size=fsize), 
	axis.title = element_text(size = fsize), 
    legend.text = element_text(size = fsize-1), 
    legend.title = element_text(size = fsize), 
    axis.ticks = element_line(size = 0.1)
  )

y.breaks <- cumsum(fig1a$counts) - fig1a$counts/2
fig1a =fig1a %>% mutate(cumulative=cumsum(counts),midpoint=cumulative-(counts/2))
fig1a_plot= ggplot(fig1a, aes(x="", y=counts, fill=disease_category))+
	geom_bar(width = 1, stat = "identity")+
	coord_polar("y", start=0)+ 
	scale_fill_grey(start = 0.6, end = 1) +  
	blank_theme + theme(legend.position="top")+
	labs(fill="Disease category")+
	scale_y_continuous(
        breaks=y.breaks,   # where to place the labels
        labels=fig1a$disease_category)+# the labels
    theme(legend.position="", axis.text = element_text(colour="black", size = 10))+ 
    geom_text(aes(x=1.2, y=midpoint, label=counts), color="black", fontface="bold", size=3)


ggsave('Fig1a.pdf', fig1a_plot, path='.', width=6, height=6)


# Figure 1B
disease_colors=brewer.pal(12,"Paired")
col_panelB=c(grey.colors(n=11,start = 0.6, end = 1)[1:4],disease_colors[10])


fig1b_plot= ggplot(fig1b, aes(x=bin, y=pct_genes, fill=DISEASE))+
	geom_bar(stat="identity", position="dodge", color="black")+ 
	scale_fill_manual(values=col_panelB,name="",guide = guide_legend(nrow=2)) +
	labs(x='Median TPM', y='% Genes expressed in blood')+
	geom_text(stat='identity',aes(label=fig1b$DISEASE),vjust=1,hjust=1 ,color="white", size=fsize/3, position = position_dodge(width=1))+
	RD_theme+
	coord_flip()+
	#geom_text(aes(x=bin, y=6, label=pct_in_blood_bin_df$DISEASE), color="white", fontface="bold", size=3.3, position = position_dodge())+
	theme(legend.position="")


ggsave('Fig1b.pdf', fig1b_plot, path='.', width=6, height=6)


# Figure 1
fig1_plot=ggdraw()+draw_plot(fig1a_plot, 0,0,1/2,1)+
	draw_plot(fig1b_plot, 1/2,1/3,1/2,2/3)+
	draw_plot_label(c('a', 'b'), c(0,1/2), c(1,1), size = 15)

#combined_plots
pdf('Figure1.pdf', w=9, h=9)
fig1_plot
dev.off()

## NOTE: Final version of this plot was modified using inkscape for aesthetics purposes

