# =======================================================================================================
# This is a script for generating Figure3: Splicing outlier detection
# #
# input:
#       1. Figure3.in.RData
#          Data generated by running Figure3_getdata.R
#
# output:
#       1. Figure3B.pdf, Figure3C.pdf, Figure3D.pdf,Figure3E.pdf
#       2. Figure3.out.RData
#          Store all data used and generated by running this script
#
# Note that the final figure was generated by using inkscape by combining figures from this script for visualization purposes
#
# =======================================================================================================



#!/bin/R

#Libraries
library(ggplot2)
library(dplyr)
library(cowplot)
library(RColorBrewer)
library(ggpubr)
library(ggbeeswarm)
rm(list=ls())


fsize=15
RD_theme=theme_classic()+
	theme(axis.text.x= element_text(size=fsize),
	axis.text.y= element_text(size=fsize), 
	axis.title = element_text(size = fsize), 
    legend.text = element_text(size = fsize-1), 
    legend.title = element_text(size = fsize), 
    axis.ticks = element_line(size = 0.1),
	strip.background=element_blank(),
	panel.grid.major=element_blank(),
	panel.grid.minor=element_blank(),
	axis.text=element_text(size=9),
	panel.border=element_blank()) 




# Master directory
dir = Sys.getenv('RARE_DIS_DIR')



#  Load input data
load(file = paste(dir,"/analysis/manuscript/figures_revision/Figure3.in.RData",sep=""))

#--- MAIN

# Figure 3B
fig_3b_zscore_thres=ggplot(sample_outlier.df.m, aes(x=as.factor(variable), y=value+1))+
	geom_boxplot(color="black", fill="grey")+#fill="#028482")+
	#stat_summary(fun.y=mean, geom="point", size=2, color="#028482")+ 
	#stat_summary(fun.data=data_summary, geom="pointrange", color="black", size=1)+
	#scale_fill_brewer(palette="Paired",name="Affected status")+
	scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),labels = scales::trans_format("log10", scales::math_format(10^.x)))+
	labs(x="Z-score threshold", y="Number of genes with\nat least one outlier")+RD_theme #+theme(legend.position="bottom")
fig_3b_zscore_thres


ggsave('Figure3B.pdf', fig_3b_zscore_thres,  path=paste(dir,"/analysis/manuscript/figures_revision/", sep=""), width=6, height=6)




# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Figure 3C
col_splic_out=c( "#87907D"	,"#AAB6A2", 	"#666666")

RV_out_plot_withsgl=ggplot(RV_outliers.m_withsgl, aes(x=variable, y=value+1, fill=filter)) + 
geom_boxplot()+ 
scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),labels = scales::trans_format("log10", scales::math_format(10^.x)))+
scale_fill_manual(values=col_splic_out, name="Data filtered for\nsplicing outliers")+
scale_x_discrete(breaks=c("RV_number_MAF0", "RV_number_MAF0.1", "RV_number_MAF1"), labels=c("0", "0.1", "1"))+
labs(x="MAF (%)", y="Number of rare variants")+facet_grid(  . ~variant_data , scales="free_y")+RD_theme +theme(legend.position=c(0.4,0.9))

RV_out_plot_withsgl
ggsave('Figure3C.pdf', RV_out_plot_withsgl,  path=paste(dir,"/analysis/manuscript/figures_revision/", sep=""), width=10, height=10)



# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Figure 3 D
## Influence of filtering on splicing outlier results
# plot results
filter_withsglt.case.plot=ggplot(sample_outlier_filter_withsgl.df.m.cases, aes(x=variable, y=value, fill=variable) )+ 
	geom_boxplot(color="black", notch=F, show.legend = FALSE)+
	geom_point(size = 0, stroke = 0)+
	scale_fill_manual(values=rep("lightgrey", 8), breaks=c("prop_pLI","prop_HPO","prop_RV", "prop_RVpLI", "prop_CADD","prop_RVHPO", "prop_RVHPOCADD","prop_combined"),
		labels=c(expression("pLI " >="0.9"), "HPO match", expression("Rare variant within 20bp","1 + 3","3 + CADD score  " >= "10"), "2 + 3", "2 + 5", "1 + 2 + 3 + 5"), name="Filter")+
	scale_x_discrete(breaks=c("prop_pLI","prop_HPO","prop_RV", "prop_RVpLI", "prop_CADD","prop_RVHPO", "prop_RVHPOCADD","prop_combined"),
		labels=c("1", "2", "3","4","5", "6", "7", "8"))+
	labs(x="Filter", y="Proportion of outlier genes") + RD_theme +guides(fill = guide_legend(override.aes = list(size = 4,shape =c(49,50,51,52,53,54,55,56))))+theme(legend.position = c(0.8,0.8))
filter_withsglt.case.plot
ggsave('Figure3D.pdf', filter_withsglt.case.plot,  path=paste(dir,"/analysis/manuscript/figures_revision/", sep=""), width=8, height=3)

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

# Figure 3 E
RV_filters_plot=ggboxplot(RV_count.m%>% filter(variable %in% c("outliers","outlier_RV_CADD_HPO_junc")), x = "variable", y = "value", color = "variable", palette =c("#C0C0C0", "#336699"), add = "jitter", shape = "variable")+
	#stat_compare_means(comparisons = custom_comparisons, label = "p.signif")+
	stat_compare_means(comparisons = custom_comparisons)+
	scale_x_discrete(labels= c( "Z-score >=2", "+ RV within 20bp junction\n+ HPO match"))+
	RD_theme+
	theme(legend.position="")+
	labs(x="Filter", y="Median number of rare variants per gene")

ggsave('Figure3E.pdf', RV_filters_plot,  path=paste(dir,"/analysis/manuscript/figures_revision/", sep=""), width=3, height=6)


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

# Figure 3 F


color = grDevices::colors()[grep('gr(a|e)y', grDevices::colors(), invert = T)]
mycol=sample(color, length(cases))

median.quartile <- function(x){
	out <- quantile(x, probs = c(0.25,0.5,0.75))
	names(out) <- c("ymin","y","ymax")
	return(out) 
}

ggplot(exp_outlier_number.df, aes(x = log10(value+1), y = filter, colour = sample)) +#geom_path(group=sample, colour="grey") + 
	stat_summary(fun.data="median.quartile",geom="pointrange", na.rm=T, color="black") + 
	#geom_quasirandom(groupOnX=FALSE) +
	theme(legend.position="")#+ 
	#scale_colour_manual(values=mycol) 
res_splicing_number.df=data.frame(variable=res_splicing_number.df$variable, value=unlist(res_splicing_number.df$value),SAMPLE=unlist(res_splicing_number.df$SAMPLE) )
all_ind_plot= ggplot(res_splicing_number.df, aes(variable,value))+ 
 	geom_quasirandom(aes(y =value, x = variable, colour = SAMPLE))+
 	stat_summary(fun.data = median.quartile, geom = "pointrange",position=position_nudge(x=0.5,y=0))+
	coord_flip()+
	#geom_path(group=sample, colour="grey")+
 	theme(legend.position="")+
 	scale_colour_manual(values=mycol) +
 	labs(y="log10(Number of genes +1)",x="Filter")+
 	scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),labels = scales::trans_format("log10", scales::math_format(10^.x))) 

all_ind_plot

ggsave('Figure3F.pdf', all_ind_plot,  path=paste(dir,"/analysis/manuscript/figures_revision/", sep=""), width=8, height=8)



# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

## combined_plot
figure3=ggdraw()+draw_plot(fig_3b_zscore_thres, 2/3,2/3,1/3,1/3)+
	draw_plot(RV_out_plot_withsgl, 0,5/12,1/2,1/4)+
	draw_plot(filter_withsglt.case.plot, 1/2,5/12,1/2,1/4)+
	draw_plot(RV_filters_plot, 0,0,1/3,5/12)+
	draw_plot(all_ind_plot, 1/3,0,2/3,5/12)+
	draw_plot_label(c('A', 'B', 'C','D', 'E', 'F'), c(0,2/3,0, 1/3,0, 1/3), c(1,1,8/12,8/12,5/12,5/12), size = 20)
figure3
pdf(paste(dir,"/analysis/manuscript/figures_revision/Figure3.pdf", sep=""), w=12, h=12)
figure3
dev.off()




# Save data
save.image(file = paste(dir,"/analysis/manuscript/figures_revision/Figure3.out.RData",sep=""))

