#!/bin/R


rm(list=ls())


# Master directory
dir = Sys.getenv('RARE_DIS_DIR')
## FUNCTIONS

source(paste(dir,"/scripts/manuscript_analyses/Figures_source.R". sep="")




#Libraries
library(ggplot2)
library(dplyr)
library(readr)
library(stringr)
library(tidyr)
library(sva)
library(cowplot)
library(purrr)
library(broom)
library(reshape2)
library(ggfortify)
library(gridExtra)
library(data.table)
library(annotables)
library(corrplot)
library(RColorBrewer)
library(qvalue) 
library(ggpubr)
library(missMDA)


#--- MAIN
# Get metadata
metadata = paste(dir,"/data/metadata/2018_06_12_Rare_Disease_Metadata.tsv",sep="")
metadata = read_tsv(metadata) %>% filter(in_freeze=="yes") %>% filter(source_of_RNA=="Blood")

# Get metadata info for pivus and dgn
meta_pivus=paste(dir,"/data/metadata/PIVUS_RNASequencingInfo.csv",sep="")
meta_pivus=read_csv(meta_pivus) %>% filter(Age=="70") %>% filter(RunOK=="Yes")
meta_pivus2=paste(dir,"/data/metadata/Pivus_expCovariatesAll_unscaled.txt",sep="")
meta_pivus2=read_tsv(meta_pivus2)%>% filter(Age==0) 

# Read in annotation files linking HPO terms genes and phenotypes
gene_to_pheno=paste(dir,"/data/metadata/gene_to_phenotype.tsv"
gene_to_pheno = read_tsv(gene_to_pheno)
colnames(gene_to_pheno)=c("entrez", "symbol", "DiseaseId")

pheno_annot=paste(dir,"/data/metadata/phenotype_annotation.tsv"
pheno_annot=read_tsv(pheno_annot)
pheno_annot=pheno_annot %>% select(HPO_terms_ID,database_INDEX, number_unknown)

# Read in and process alternative HPO files (generated by parse_hpoterms.py)
parent_terms=paste(dir,"/data/metadata/parent_terms_hpo_2018_03_16.txt",sep="")
child_terms=paste(dir,"/data/metadata/child_terms_hpo_2018_03_16.txt",sep="")
altid_terms=paste(dir,"/data/metadata/altid_terms_hpo_2018_03_16.txt",sep="")

altid_terms=as.data.frame(read.table(altid_terms, header=F, sep="\t"))
colnames(altid_terms)=c("HPO_ID", "ALT_ID")
child_terms=as.data.frame(read.table(child_terms, header=F, sep="\t"))
colnames(child_terms)=c("HPO_ID", "ALT_ID")
parent_terms=as.data.frame(read.table(parent_terms, header=F, sep="\t"))
colnames(parent_terms)=c("HPO_ID", "ALT_ID")


# generates list of HPO alternative IDs from the input files
alt_hpo_ids_list=lapply(altid_terms$HPO_ID,get_hpo_alt_id, altid_terms=altid_terms)
names(alt_hpo_ids_list)=altid_terms$HPO_ID
child_hpo_ids_list=lapply(child_terms$HPO_ID,get_hpo_alt_id, altid_terms=child_terms)
names(child_hpo_ids_list)=child_terms$HPO_ID
parent_hpo_ids_list=lapply(parent_terms$HPO_ID,get_hpo_alt_id, altid_terms=parent_terms)
names(parent_hpo_ids_list)=parent_terms$HPO_ID

# For every ID associated with the disease, get list of alternative Ids, child ids and parent ids
# make a list for each case with HPO terms

cases=metadata %>% filter(affected_status=="Case") %>% select(sample_id) %>% pull

# Get list of HPO terms from metadata file
HPOs=lapply(cases,get_list_hpo, metadata)
names(HPOs)=cases
cases_withGen=metadata %>% filter(variant_data !="none", affected_status=="Case")%>% select(sample_id) %>% pull

# Generate extended list of HPO terms for each sample
HPO_extended=lapply(cases, process_sample_ids_hpo, HPO_list=HPOs)
names(HPO_extended)=cases


HPO_extended <- Map(cbind, HPO_extended, sample = names(HPO_extended))
HPO_extended.df=as.data.frame(do.call("rbind", HPO_extended))
colnames(HPO_extended.df)=c("HPO_term", "sample")
HPO_extended.df$sample=as.character(HPO_extended.df$sample)


# attach gene to HPO ids for each samples
HPO_extended.df=HPO_extended.df %>% left_join(pheno_annot, by=c("HPO_term"="HPO_terms_ID"), all.left=T) %>% select(HPO_term,sample,database_INDEX) %>% left_join(gene_to_pheno, by=c("database_INDEX"="DiseaseId"), all.left=T) %>% select(HPO_term,sample,database_INDEX,symbol) %>% left_join(grch37, by="symbol", all.left=T)  %>% select(HPO_term,sample, ensgene) %>% unique %>% filter(!is.na(ensgene))


# get affected status data
affected_status_df=read.table(paste(dir,"/analysis/outlier_analysis/splicing/for_freeze/sample_affected_status_freeze_RD_PIVUS.tsv", sep=""), header=F)
colnames(affected_status_df)=c('sample', 'status')

affected_status_df$cohort=c(rep("RD",87), rep("PIVUS", 68))


#get splicing z-scores
zscores_blood =as.data.frame(read.table(paste(dir, "/analysis/outlier_analysis/splicing/for_freeze/RD_freeze_junc_outliers_PCAratio_blood_nf_PIVUS_withPIVsamples_withmisdata.txt", sep=""), sep="\t", header=T))

zscores_blood =zscores_blood %>% mutate(gene=unlist(strsplit(as.character(gene),"[.]"))[c(TRUE,FALSE)]) 
genes=zscores_blood %>% select(gene) %>% distinct %>% pull

#get splicing z-scores filtered with rare variants data

RV_outlier_file=paste(dir, "/analysis/outlier_analysis/splicing/for_freeze/RV/RD_freeze_junc_outliers_PCAratio_blood_nf_PIVUS_withPIVsamples_withmisdata_sorted_RV_window.txt", sep="")'/srv/scratch/restricted/rare_diseases/analysis/outlier_analysis/splicing/for_freeze/ifrun9/RV/RD_freeze_junc_outliers_PCAratio_blood_nf_PIVUS_withPIVsamples_withmisdata_sorted_RV_window.txt'
RV_outlier=as.data.frame(read.table(RV_outlier_file, sep="\t", header=F))
colnames(RV_outlier)=c(colnames(zscores_blood), "chr_var", "start_var", "end_var", "ref_var", "alt_var", "gnomAD_AF", "raw_cadd", "phred_cadd", "chr_gene", "start_gene", "end_gene", "gene_name")

# make a column with singleton included in the analysis
RV_outlier =RV_outlier %>% mutate(gnomAD_AF_withsgl = replace(gnomAD_AF, gnomAD_AF==".", 0))


# format variant data so that only the max observed allele frequency is kept for variant were several frequencies are available
RV_outlier$gnomAD_AF_filt_withsgl=sapply(RV_outlier$gnomAD_AF_withsgl,process_variant)

#filter for RV with MAF<=0.1%
maf=0.001
RV_outlier_filt_withsgl=RV_outlier %>% filter(!is.na(gnomAD_AF_filt_withsgl)) %>% filter(gnomAD_AF_filt_withsgl <=maf)
RV_outlier_filt_withsgl =RV_outlier_filt_withsgl %>% mutate(gene_name=str_extract(gene_name, "ENSG[0-9]+"))


# Make dataframe containing the number of genes with at least 1 outlier at different Zscore thresholds
sample_outlier.df=data.frame(sample_id=all_samples,
	"Z2"=sapply(all_samples, get_outlier_genes, threshold=2, outlier_df.m=zscores_blood, 0),
	"Z3"=sapply(all_samples, get_outlier_genes, threshold=3, outlier_df.m=zscores_blood, 0),
	"Z4"=sapply(all_samples, get_outlier_genes, threshold=4, outlier_df.m=zscores_blood, 0),
	"Z5"=sapply(all_samples, get_outlier_genes, threshold=5, outlier_df.m=zscores_blood, 0),
	"Z6"=sapply(all_samples, get_outlier_genes, threshold=6, outlier_df.m=zscores_blood, 0),
	affected_status=sapply(all_samples,get_affected_status, affected_status_df=affected_status_df))

# Add cohort information to data frame
sample_outlier.df=sample_outlier.df %>% left_join(affected_status_df, by=c("sample_id"="sample")) %>% select(-status) 

# transform data for plotting
sample_outlier.df.m=melt(sample_outlier.df,id.vars=c("sample_id","affected_status", "cohort"))
sample_outlier.df.m$variable=c(rep(2,152),rep(3,152),rep(4,152), rep(5,152), rep(6,152))


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Figure 3C
# number of RV
RV_junc_dir=paste(dir, "/analysis/outlier_analysis/splicing/for_freeze/RV/",sep="")
RV_junc_samples=list.files(pattern='_junction_RV_window.txt', path=RV_junc_dir)


bed_dir=paste(dir, "/data/bed/for_freeze_exac_filt/", sep="")

# count the number of RV nearby annotated junctions for each sample
RV_junction_number=data.frame(sample=sample_with_data, RV_number_MAF0=sapply(sample_with_data, get_number_junction_RV_window, RV_junc_dir, 0, "yes"), RV_number_MAF0.1=sapply(sample_with_data, get_number_junction_RV_window, RV_junc_dir, 0.001, "yes"),RV_number_MAF1=sapply(sample_with_data, get_number_junction_RV_window, RV_junc_dir, 0.01, "yes"))
RV_junction_number=RV_junction_number %>% left_join(metadata,by=c("sample"="sample_id")) %>% select(sample, RV_number_MAF0,RV_number_MAF0.1,RV_number_MAF1,variant_data, affected_status)#%>% rename(variant_data=variant_data.x, affected_status=affected_status.x)
RV_junction_number=RV_junction_number%>% mutate(filter="RV near junction")%>% mutate(splicing_data="no")%>% mutate(singleton="yes")

# count the number of RV  for each sample
RV_number_withsgl=data.frame(sample=sample_with_data, RV_number_MAF0=sapply(sample_with_data, get_number_RV, bed_dir, 0, "yes"), RV_number_MAF0.1=sapply(sample_with_data, get_number_RV, bed_dir, 0.001, "yes"),RV_number_MAF1=sapply(sample_with_data, get_number_RV, bed_dir, 0.01, "yes"))
RV_number_withsgl=RV_number_withsgl %>% left_join(metadata,by=c("sample"="sample_id")) %>% select(sample, RV_number_MAF0,RV_number_MAF0.1,RV_number_MAF1,variant_data, affected_status)#%>% rename(variant_data=variant_data.x, affected_status=affected_status.x)
RV_number_withsgl=RV_number_withsgl%>% mutate(filter="Rare variant")%>% mutate(splicing_data="no")%>% mutate(singleton="yes")

# data with splicing outliers
RV_number_out_withsgl=data.frame(sample=sample_with_data, RV_number_MAF0=sapply(sample_with_data, get_number_RV_outlier_window,RV_outlier,3, 0,  "yes"), RV_number_MAF0.1=sapply(sample_with_data, get_number_RV_outlier_window,RV_outlier,3, 0.001, "yes"),RV_number_MAF1=sapply(sample_with_data, get_number_RV_outlier_window,RV_outlier,3, 0.01, "yes"))
RV_number_out_withsgl=RV_number_out_withsgl %>% left_join(metadata,by=c("sample"="sample_id")) %>% select(sample, RV_number_MAF0,RV_number_MAF0.1,RV_number_MAF1,variant_data, affected_status)
RV_number_out_withsgl=RV_number_out_withsgl %>% mutate(filter="splicing outlier")%>% mutate(splicing_data="yes")%>% mutate(singleton="yes")


# combine info of RV and splicing outlier
RV_outliers=rbind(RV_junction_number,RV_number_withsgl,RV_number_out_withsgl)

# melt DF for plot
RV_outliers.m=melt(RV_outliers,id.var=c("sample", "variant_data", "affected_status", "filter", "splicing_data", "singleton"))

RV_outliers.m_withsgl=RV_outliers.m %>% filter(singleton=="yes", variable!="RV_number_MAF0")


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Figure 3 D
## Influence of filtering on splicing outlier results
zscore_threshold=2
distance_threshold=20
cadd=10
pli=0.9

sample_outlier_filter_withsgl.df=data.frame(sample_id=sample_with_data,
	"raw"=sapply(sample_with_data, get_outlier_genes, threshold=zscore_threshold, outlier_df.m=zscores_blood, pLI_thre=0),
	"raw.Lof"=sapply(sample_with_data, get_outlier_genes, threshold=zscore_threshold, outlier_df.m=zscores_blood, pLI_thre=pli),
	"raw.HPO"=sapply(sample_with_data,get_hpo_match_nb,outlier_file=zscores_blood,HPOs_list=HPO_extended, pLI_thre=0),
	"RV"=sapply(sample_with_data, get_outlier_genes_RV_window, threshold=zscore_threshold, outlier_df.m=RV_outlier_filt_withsgl, CADD=0, pLI_thre=0),
	"RV.LoF.intolerant"=sapply(sample_with_data, get_outlier_genes_RV_window, threshold=zscore_threshold, outlier_df.m=RV_outlier_filt_withsgl, CADD=0, pLI_thre=pli),
	"RV.CADD"=sapply(sample_with_data, get_outlier_genes_RV_window, threshold=zscore_threshold, outlier_df.m=RV_outlier_filt_withsgl,CADD=cadd, pLI_thre=0),
	"RV.HPO"=sapply(sample_with_data, get_hpo_match_nb_RV_window,  outlier_RV=RV_outlier_filt_withsgl, HPOs_list=HPO_extended,cadd_thres=0, pLI_thre=0),
	"RV.HPO.CADD"=sapply(sample_with_data, get_hpo_match_nb_RV_window,  outlier_RV=RV_outlier_filt_withsgl, HPOs_list=HPO_extended,cadd_thres=10, pLI_thre=0),
	"combined"=sapply(sample_with_data, get_hpo_match_nb_RV_window,  outlier_RV=RV_outlier_filt_withsgl,HPOs_list=HPO_extended, cadd_thres=cadd, pLI_thre=pli),

	institution=sapply(sample_with_data,get_institution, metadata=metadata),
	affected_status=sapply(sample_with_data,get_affected_status, affected_status_df=affected_status_df),
	technology=sapply(sample_with_data,get_technology, metadata=metadata))

save("sample_outlier_filter_withsgl.df", file="/srv/scratch/restricted/rare_diseases/analysis/outlier_analysis/splicing/for_freeze/splicing_filters_genes.RData")


# make a plot with proportions of candidates 

sample_outlier_filter_withsgl.df= sample_outlier_filter_withsgl.df %>% filter(raw!=0)
sample_outlier_filter_withsgl.df$prop_pLI=sample_outlier_filter_withsgl.df$raw.Lof/sample_outlier_filter_withsgl.df$raw
sample_outlier_filter_withsgl.df$prop_HPO=sample_outlier_filter_withsgl.df$raw.HPO/sample_outlier_filter_withsgl.df$raw
sample_outlier_filter_withsgl.df$prop_RV=sample_outlier_filter_withsgl.df$RV/sample_outlier_filter_withsgl.df$raw
sample_outlier_filter_withsgl.df$prop_RVpLI=sample_outlier_filter_withsgl.df$RV.LoF.intolerant/sample_outlier_filter_withsgl.df$raw
sample_outlier_filter_withsgl.df$prop_CADD=sample_outlier_filter_withsgl.df$RV.CADD/sample_outlier_filter_withsgl.df$raw
sample_outlier_filter_withsgl.df$prop_RVHPO=sample_outlier_filter_withsgl.df$RV.HPO/sample_outlier_filter_withsgl.df$raw
sample_outlier_filter_withsgl.df$prop_RVHPOCADD=sample_outlier_filter_withsgl.df$RV.HPO.CADD/sample_outlier_filter_withsgl.df$raw
sample_outlier_filter_withsgl.df$prop_combined=sample_outlier_filter_withsgl.df$combined/sample_outlier_filter_withsgl.df$raw
sample_outlier_filter_withsgl.df=sample_outlier_filter_withsgl.df%>% select(sample_id,institution,affected_status, technology, prop_pLI, prop_HPO,prop_RV,prop_RVpLI,prop_CADD, prop_RVHPO,prop_RVHPOCADD,prop_combined)

#melt DF
sample_outlier_filter_withsgl.df.m=melt(sample_outlier_filter_withsgl.df,id.vars=c("sample_id","affected_status", "institution", "technology"))

# select for only cases
sample_outlier_filter_withsgl.df.m.cases=sample_outlier_filter_withsgl.df.m %>% filter(affected_status=="Case")

#figure 3E

# filter for Z-score>=2
raw_genes=lapply(cases_withGen, get_outlier_genes_names, threshold=zscore_threshold, outlier_df.m=zscores_blood, pLI_thre=0)
names(raw_genes)=cases_withGen
	# remove empty fields
raw_genes=compact(raw_genes)
raw_genes <- Map(cbind, raw_genes, sample = names(raw_genes))
raw_genes.df=as.data.frame(do.call("rbind", raw_genes))
raw_genes.df$hpo=mapply(is_hpo,raw_genes.df$sample,raw_genes.df$V1)
raw_genes_hpo_percent=raw_genes.df %>% group_by(sample) %>% mutate(n_genes=n())%>% mutate(percent_hpo=sum(hpo)/n_genes) %>% select(sample,n_genes,percent_hpo)%>% filter(!duplicated(sample)) 
raw_genes_hpo_percent$method="Z-score>=2"

# Z-score >=2, RV within 20bp junction, CADD score >=10
RV_CADD_genes=lapply(cases_withGen, get_outlier_genes_RV_window_names, threshold=zscore_threshold, outlier_df.m=RV_outlier_filt_withsgl, CADD=10, pLI_thre=0)
names(RV_CADD_genes)=cases_withGen
RV_CADD_genes=compact(RV_CADD_genes)
RV_CADD_genes <- Map(cbind, RV_CADD_genes, sample = names(RV_CADD_genes))
RV_CADD_genes.df=as.data.frame(do.call("rbind", RV_CADD_genes))
RV_CADD_genes.df$hpo=mapply(is_hpo,RV_CADD_genes.df$sample,RV_CADD_genes.df$V1)
RV_CADD_genes_hpo_percent=RV_CADD_genes.df %>% group_by(sample) %>% mutate(n_genes=n()) %>% mutate(percent_hpo=sum(hpo)/n_genes)%>% select(sample,n_genes,percent_hpo)%>% filter(!duplicated(sample)) 
RV_CADD_genes_hpo_percent$method="Z-score>=2, RV, CADD>=10"

## Look at number of rare variants around genes throughout filters
RV_CADD_HPO_genes.df= RV_CADD_genes.df %>% filter(hpo==1)
RV_CADD_HPO_genes.list=split(RV_CADD_HPO_genes.df, as.character(RV_CADD_HPO_genes.df$sample))
RV_CADD_HPO_genes.list=compact(RV_CADD_HPO_genes.list)

# median number of RV per gene for each sample throughout filters
RV_count=data.frame(sample=sample_with_data,
 outliers=sapply(sample_with_data, get_number_RV_pergene, bed_dir, 0.001, "yes",raw_genes),
 outlier_RV_CADD_HPO_junc=sapply(sample_with_data, get_number_RV_pergene, bed_dir, 0.001, "yes",RV_CADD_HPO_genes.list))

RV_count.m=melt(RV_count,id.var=c("sample"))
RV_count.m.filt=RV_count.m %>% filter(variable != "raw_nonout")

custom_comparisons=list( c("outliers","outlier_RV_CADD_HPO_junc"))


# Save data
save.image(file = paste(dir,"/data/Figure3.in.RData",sep=""))


