# =======================================================================================================
# This is a script for generating EDF10: Solved case without genetic data: ASAH1 case.
#
# Note that the final figure was generated by using inkscape by combining figures from this script for visualization purposes
#
# =======================================================================================================

#!/bin/R



library(dplyr)
library(readr)
library(stringr)
library(tidyr)
library(reshape2)
library(data.table)
library(annotables)
library(ggpubr)
library(cowplot)




#Read in data
edf10=read.table("EDF10_data.txt", sep="\t", header=T)


# edf10a
edf10_plot=ggdotchart(edf10, x = "filter", y = "value",color = "category",shape='is_causal_in',
	palette=c("#D0C6B1","#FFD800", "#587058", "#587498", "#E86850"),
	sorting = "descending",add = "segments",rotate = TRUE,
	group = "category",dot.size =20,label = round(edf10$value),
	font.label = list(color = "white", size = 18, vjust = 0.5), ggtheme = theme_pubr(),
	add.params = list(color = "category", size = 2), 
	legend="", ylab="Number of candidate genes", xlab="Filter")


