# =======================================================================================================
# This is a script for generating EDF2: Correction for batch effects - Expression data.
#
# Note that the final figure was generated by using inkscape by combining figures from this script for visualization purposes
#
# =======================================================================================================




#!/bin/R

#  Read in input data
edf2c=read.table("EDF2c_data.txt", sep="\t", header=T)

## Panel A
# PCA plot of first 2 PCs uncorrected data. PC1 and PC2 data available

## Panel B
# PCA plot of first 2 PCs corrected data. PC1 and PC2 data available

## Panel C
edf2c_plot <- ggplot(data=edf2c, 
		aes(x=Var2, y=as.factor(Var1), fill=value)) + 
 	geom_tile(color="white") +
 	scale_fill_gradient2(low="blue", high="red", mid="white", midpoint=0, limit=c(-1,1), space="Lab", name="Pearson\nCorrelation") +
 	theme_minimal() + 
 	coord_fixed() + labs(x="Covariates", y="Surrogate variable") + 
 	theme(legend.position="right",
 		axis.text.x=element_text(angle=45, hjust=1),
 		axis.text=element_text(size=11),
 		axis.title=element_text(size=14)) +
 	annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf, size=1) +
	annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf, size=1)
	
