#!/bin/R
# =======================================================================================================
# This is a script for generating EDF3: Use of regression splines in expression data normalization.
#
# Note that the final figure was generated by using inkscape by combining figures from this script for visualization purposes
#
# =======================================================================================================

library(cowplot)
library(ggplot2)


## Define ggplot theme
fsize <- 15
RD_theme = theme_classic() +
	theme(axis.text.x = element_text(size=fsize),
	axis.text.y = element_text(size=fsize), 
	axis.title = element_text(size=fsize), 
    legend.text = element_text(size=fsize-1), 
    legend.title = element_text(size=fsize), 
    axis.ticks = element_line(size=0.1))

## Make plots

# EDF3A
edf3a <- read.table("EDF3a_data.txt", header=T)
edf3a_plot <- ggplot(edf3a, aes(x=sv, y=residuals)) + 
	geom_hline(yintercept=0) +
	geom_hline(yintercept=2, colour="gray", linetype="dashed") +
	geom_hline(yintercept=-2, colour="gray", linetype="dashed") +
	geom_point(aes(fill=as.factor(batch)), size=1.5, shape=21, colour="black") +
	facet_wrap( ~ cohort, scales="fixed") +
	labs(x="SV2", y="Residuals") +
	RD_theme +
	theme(panel.spacing.x=unit(1, "lines")) +
	annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf, size=1) +
	annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf, size=1) +
	scale_fill_brewer(palette="Set3")


# EDF3B
edf3b <- read.table("EDF3b_data.txt", header=T)

# EDF3C
edf3c <- read.table("EDF3c_data.txt", header=T)
edf3c_plot <- ggplot(edf3c, aes(pvalue)) +
	geom_histogram(binwidth=0.02, fill="gray40") +
	labs(x="P Value", y="Count") +
	theme_bw() +
	theme(strip.background=element_blank(),
		panel.grid.major=element_blank(),
		panel.grid.minor=element_blank(),
		axis.text=element_text(size=9),
		panel.border=element_blank()) +
	annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf, size=1) +
	annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf, size=1)


# EDF3D
edf3d <- read.table("EDF3d_data.txt", header=T)
edf3d_plot <- ggplot(data=edf3d, aes(x=gene_id, y=value)) + #
	geom_bar(stat="identity", fill="gray40") +
	geom_hline(yintercept=0) +
	labs(x="Genes", y="Change in R^2") +
	scale_x_continuous(breaks=c(1, seq(5000, 20000, 5000))) +
	theme_bw() +
	theme(strip.background=element_blank(),
		panel.grid.major=element_blank(),
		panel.grid.minor=element_blank(),
		axis.text=element_text(size=11),
		panel.border=element_blank()) +
	annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf, size=1) +
	annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf, size=1) 
