# =======================================================================================================
# This is a script for generating EDF8: Diagnostic rate after analysis of 80 distinct cases.
#
# Note that the final figure was generated by using inkscape by combining figures from this script for visualization purposes
#
# =======================================================================================================



#!/bin/R


#--- Libraries

library(cowplot)
library(ggplot2)
library(RColorBrewer)


#  Read in input data
edf8a=read.table("EDF8a_data.txt", sep="\t", header=T)
edf8b=read.table("EDF8b_data.txt", sep="\t", header=T)


# Panel A
edf8a_plot=ggplot(edf8a, aes(x=variable, y=value))+geom_bar(stat="identity", fill="grey", color="black")+
	labs(x="", y="Rate (%)") + scale_x_discrete(labels=c("solved" = "Solved", "strong_candidate" = "Strong Candidate", "unsolved" = "Unsolved"))


# Panel B
edf8b_plot=ggplot(edf8b, aes(x=variable, y=value))+ geom_boxplot(fill="grey", color="black") +
	labs(x="",y="Percentage of cases for which\ncandidate gene is in final list")+
	scale_x_discrete(labels=c("shuffle_candidate" = "Shuffling Candidate", "shuffle_gene" = "Shuffling genes", "real_data" = "Real data"))

