# =======================================================================================================
# This is a script for generating FigureS9: Correction for batch effects - Splicing data
# #
# input:
#       1. FigureS10.in.RData
#          Data generated by running FigureS10_getdata.R
#
# output:
#       1. FigureS10.pdf
#       2. FigureS10.out.RData
#          Store all data used and generated by running this script
#
# Note that the final figure was generated by using inkscape by combining figures from this script for visualization purposes
#
# =======================================================================================================



#!/bin/R


# look at the number of outliers depending on the junction number




#--- Libraries
library(cowplot)
library(ggplot2)
library(RColorBrewer)
library(ggpubr)


# Master directory
dir = Sys.getenv('RARE_DIS_DIR')

#  Load input data
load(file = paste(dir,"/data/FigureS10.in.RData",sep=""))

custom_comparisons=list(levels(z2$juncbin)[c(1,2)],levels(z2$juncbin)[c(2,3)],levels(z2$juncbin)[c(3,4)],levels(z2$juncbin)[c(1,4)])

junction_impact_out=ggplot(z2, aes(x=juncbin, y=average, color=affected_status))+ 
	geom_boxplot() +
	scale_colour_grey(name="Affected Status") +
	stat_compare_means( comparisons=custom_comparisons)+
	theme(legend.position="top")+
	labs(x="Number of junctions", y="Average number of outliers per gene") 

ggsave('FigureS10.pdf', junction_impact_out, path=paste(dir,"/analysis/manuscript/figures/", sep=""), width=6, height=6)


# Save data
save.image(file = paste(dir,"/data/FigureS10.out.RData",sep=""))
