# =======================================================================================================
# This is a script for generating FigureS14: GDiagnostic  rate  after  analysis  of  47  distinct  cases
# #
# output:
#       1. FigureS14.pdf
#       2. FigureS14.out.RData
#          Store all data used and generated by running this script
#
# Note that the final figure was generated by using inkscape by combining figures from this script for visualization purposes
#
# =======================================================================================================


# Master directory
dir = Sys.getenv('RARE_DIS_DIR')

#Libraries
library(ggplot2)
library(dplyr)
library(readr)
library(RColorBrewer)

fsize=15
RD_theme=theme_classic()+
	theme(axis.text.x= element_text(size=fsize),
	axis.text.y= element_text(size=fsize), 
	axis.title = element_text(size = fsize), 
    legend.text = element_text(size = fsize-1), 
    legend.title = element_text(size = fsize), 
    axis.ticks = element_line(size = 0.5),
	strip.background=element_blank(),
	panel.grid.major=element_blank(),
	panel.grid.minor=element_blank(),
	axis.text=element_text(size=fsize),
	panel.border=element_blank()) 


diag=read.table(paste(dir,"/data/diagnostic_rate.txt", sep=""), header=T)
diag$status=factor(diag$status, levels=c("solved", "linked_to_phenotype", "not_directly_linked_to_phenotype","unsolved"))


diag_rate_plot=ggplot(diag, aes(x=status,y=proportion, fill=status))+
	geom_bar(stat="identity")+
	scale_fill_manual(values=c("#C25B56", "#BEB9B5", "#96C0CE", "#525564"))+
	RD_theme+
	theme(legend.position="")+
	scale_y_continuous(name="Proportion of undiagnosed diseases", limits=c(0, 0.7))+ labs(x="")+
	scale_x_discrete(labels=c("solved" = "solved", "linked_to_phenotype" = "linked to\n phenotype","not_directly_linked_to_phenotype" = "no direct link\n to phenotype", "unique_ASE"= "ASE","unsolved"="no candidate"))
ggsave('FigureS14.pdf', diag_rate_plot, path=paste(dir,"/analysis/manuscript/figures/", sep=""), width=10, height=6)



# Save data
save.image(file = paste(dir,"/data/FigureS14.out.RData",sep=""))


