# =======================================================================================================
# This is a script for generating FigureS8: Percentage of samples with at least one candidate genes when filtering outliers
# #
# input:
#       1. FigureS8.in.RData
#          Data generated by running FigureS8_getdata.R
#
# output:
#       1. FigureS2A.pdf, FigureS2B.pdf, FigureS2.pdf
#       2. FigureS2.out.RData
#          Store all data used and generated by running this script
#
# Note that the final figure was generated by using inkscape by combining figures from this script for visualization purposes
#
# =======================================================================================================



#!/bin/R


#  Load input data
load(file = paste(dir,"/data/FigureS8.in.RData",sep=""))

#Libraries
library(ggplot2)
library(cowplot)
library(RColorBrewer)


fsize=15
RD_theme=theme_classic()+
	theme(axis.text.x= element_text(size=fsize),
	axis.text.y= element_text(size=fsize), 
	axis.title = element_text(size = fsize), 
    legend.text = element_text(size = fsize-1), 
    legend.title = element_text(size = fsize), 
    axis.ticks = element_line(size = 0.1),
	strip.background=element_blank(),
	panel.grid.major=element_blank(),
	panel.grid.minor=element_blank(),
	axis.text=element_text(size=9),
	panel.border=element_blank()) 

# Panel A
exp_non_zero_samples_plot=ggplot(non_zero_samples, aes(x=as.factor(filter), y=value)) + 
  geom_point(size=3) + 
  geom_segment(aes(x=filter, xend=filter, y=0, yend=value)) +
  xlab("Filter")+ ylab("% samples with at least 1 candidate gene")+ RD_theme
ggsave('FigureS8A.pdf', non_zero_samples_plot, path=paste(dir,"/analysis/manuscript/figures/", sep=""), width=4.5, height=6)


# Panel B
spli_non_zero_samples_plot=ggplot(spli_non_zero_samples, aes(x=as.factor(filter), y=value)) + 
  geom_point(size=3) + 
  geom_segment(aes(x=filter, xend=filter, y=0, yend=value)) +
  xlab("Filter")+ ylab("% samples with at least 1 candidate gene")+ RD_theme
ggsave('FigureS8B.pdf', non_zero_samples_plot,  path=paste(dir,"/analysis/manuscript/figures/", sep=""), width=4, height=6)



## combined_plot
sup_percent_nonzero_plot=ggdraw()+draw_plot(exp_non_zero_samples_plot, 0,0,1/2,1)+
	draw_plot(spli_non_zero_samples_plot, 1/2,0,1/2,1)+
	draw_plot_label(c('A', 'B'), c(0,1/2), c(1,1), size = 20)

sup_percent_nonzero_plot

pdf(paste(dir,"/analysis/manuscript/figures/FigureS8.pdf",sep=""), w=11, h=8)
sup_percent_nonzero_plot
dev.off()

# Save data
save.image(file = paste(dir,"/data/FigureS8.out.RData",sep=""))

