# =======================================================================================================
# This is a script for generating FigureS13: Genetic data across rare disease samples
# #
# input:
#       1. FigureS13.in.RData
#          Data generated by running FigureS13_getdata.R
#
# output:
#       1. FigureS13A.pdf, FigureS13B.pdf, FigureS13.pdf
#       2. FigureS13.out.RData
#          Store all data used and generated by running this script
#
# Note that the final figure was generated by using inkscape by combining figures from this script for visualization purposes
#
# =======================================================================================================

# Master directory
dir = Sys.getenv('RARE_DIS_DIR')

#Libraries
library(ggplot2)
library(cowplot)
library(RColorBrewer)


#  Load input data
load(file = paste(dir,"/data/FigureS13.in.RData",sep=""))



fsize=15
RD_theme=	theme(axis.text.x= element_text(size=fsize),
	axis.text.y= element_text(size=fsize), 
	axis.title = element_text(size = fsize), 
    legend.text = element_text(size = fsize-1), 
    legend.title = element_text(size = fsize), 
    axis.ticks = element_line(size = 0.1))

# Panel A
color_variant=c( "#2F4E6F", "#98B1C4", "#C8D7E3")

data_summary_plot=ggplot(genome_data_summary, aes(x=institution, y=variant_info_n, fill=variant_data))+
	geom_bar(stat="identity", position=position_dodge(), color="black")+
	facet_grid(.~affected_status)+
	scale_fill_manual(values=color_variant,name="Variant data")+
	labs(x="Institution", y="Number of samples")+RD_theme +
	theme(legend.position=c(0.5,0.8))+ scale_y_continuous(breaks= pretty_breaks())

ggsave('FigureS13A.pdf', data_summary_plot,path=paste(dir,"/analysis/manuscript/figures/", sep=""), width=6, height=6)


# Panel B
colors_lof=c("#9DB2B1","#D6E4E1", "#BFCFCC")
LOF_variants.plot=ggplot(variant_features.lof, aes(x=indiv_id,y=value,fill=variable))+ geom_bar(stat="identity")+ 
	scale_fill_manual(values=colors_lof,name="Variant type")+
	labs(x="Sample", y="Number of variants")+ RD_theme +
	theme(axis.text.x=element_blank(),legend.position=c(0.05,0.85))+ scale_y_continuous(breaks= pretty_breaks())
ggsave('FigureS13B.pdf', LOF_variants.plot,path=paste(dir,"/analysis/manuscript/figures/", sep=""), width=6, height=6)


variants_combined_plot=ggdraw()+draw_plot(data_summary_plot, 0,0,1/2,1)+
	draw_plot(LOF_variants.plot, 1/2,0,1/2,1)+
	draw_plot_label(c('A', 'B'), c(0,1/2), c(1,1), size = 20)

pdf(paste(dir,"/analysis/manuscript/figures/FigureS13.pdf". sep=""), w=16, h=8)
variants_combined_plot
dev.off()


# Save data
save.image(file = paste(dir,"/data/FigureS13.out.RData",sep=""))

