# =======================================================================================================
# This is a script for generating FigureS11: Affected status and cohort effect on splicing Z-score
# #
# input:
#       1. FigureS11.in.RData
#          Data generated by running FigureS10_getdata.R
#
# output:
#       1. FigureS11A.pdf, FigureS11B.pdf, FigureS11.pdf
#       2. FigureS11.out.RData
#          Store all data used and generated by running this script
#
# Note that the final figure was generated by using inkscape by combining figures from this script for visualization purposes
#
# =======================================================================================================


#!/bin/R


#Libraries
library(ggplot2)
library(cowplot)
library(RColorBrewer)

# Master directory
dir = Sys.getenv('RARE_DIS_DIR')

#  Load input data
rm(list=ls())
load(file = paste(dir,"/data/FigureS11.in.RData",sep=""))

fsize=15
RD_theme=theme_classic()+
	theme(axis.text.x= element_text(size=fsize),
	axis.text.y= element_text(size=fsize), 
	axis.title = element_text(size = fsize), 
    legend.text = element_text(size = fsize-1), 
    legend.title = element_text(size = fsize), 
    axis.ticks = element_line(size = 0.1),
	strip.background=element_blank(),
	panel.grid.major=element_blank(),
	panel.grid.minor=element_blank(),
	axis.text=element_text(size=9),
	panel.border=element_blank()) 

# Panel A
zscore_thres_case_control_plot=ggplot(sample_outlier.df.m, aes(x=as.factor(variable), y=value+1, fill=affected_status))+
	geom_boxplot()+
	scale_fill_brewer(palette="Paired",name="Affected status")+
	scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),labels = scales::trans_format("log10", scales::math_format(10^.x)))+
	labs(x="Zscore threshold", y="Number of genes with\nat least one outlier")+
	RD_theme +
	theme(legend.position=c(0.8,0.5))+
	stat_compare_means(aes(group = affected_status), label = "p.signif")

ggsave('FigureS11A.pdf', zscore_thres_case_control_plot, path=paste(dir,"/analysis/manuscript/figures_revision/", sep=""), width=6, height=6)

# Panel B

zscore_thres_cohort=ggplot(sample_outlier.df.m, aes(x=as.factor(variable), y=value+1, fill=cohort))+
	geom_boxplot()+
	scale_fill_brewer(palette="Reds",name="Cohort")+
	scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),labels = scales::trans_format("log10", scales::math_format(10^.x)))+
	labs(x="Z-score threshold", y="Number of genes with\nat least one outlier")+
	RD_theme +
	theme(legend.position=c(0.8,0.9))+
	stat_compare_means(aes(group = cohort), label = "p.signif")

ggsave('FigureS11B.pdf', zscore_thres_cohort, path=paste(dir,"/analysis/manuscript/figures_revision/", sep=""), width=6, height=6)


## combined_plot
sup_zscore_thres_plot=ggdraw()+draw_plot(zscore_thres_case_control_plot, 0,1/2,1,1/2)+
	draw_plot(zscore_thres_cohort, 0,0,1,1/2)+
	draw_plot_label(c('A', 'B'), c(0,0), c(1,1/2), size = 20)


pdf(paste(dir,"/analysis/manuscript/figures_revision/FigureS11.pdf", sep=""), w=8, h=10)
sup_zscore_thres_plot
dev.off()

# Save data
save.image(file = paste(dir,"/analysis/manuscript/figures_revision/FigureS11.out.RData",sep=""))


