
# =======================================================================================================
# This is a script for generating FigureS15: Candidates filters for sister of proband in RARS2case
# #
# input:
#       1. FigureS15.in.RData
#          Data generated by running FigureS15_getdata.R
#
# output:
#       1. FigureS11A.pdf, FigureS11B.pdf, FigureS11.pdf
#       2. FigureS11.out.RData
#          Store all data used and generated by running this script
#
# Note that the final figure was generated by using inkscape by combining figures from this script for visualization purposes
#
# =======================================================================================================


#!/bin/R


#Libraries
library(ggplot2)
library(cowplot)
library(RColorBrewer)




rars2_RD059.dotchart2=ggdotchart(rars2_RD059.df.m, x = "variable", y = "value",color = "category",shape='is_causal_in',
	palette=c("#D0C6B1","#FFD800", "#587058", "#587498", "#E86850"),
	sorting = "descending",add = "segments",rotate = TRUE,
	group = "category",dot.size = 14.5,label = round(rars2_RD059.df.m$value),
	font.label = list(color = "white", size = 13, vjust = 0.5), ggtheme = theme_pubr(),
	add.params = list(color = "category", size = 2), 
	legend=c(0.7,0.7), ylab="Number of candidate genes", xlab="Filter")#+RD_theme


pdf(paste(dir,"/analysis/manuscript/figures/FigureS15.pdf", sep=""), height=8, width=8)
rars2_RD059.dotchart2

dev.off()

