# =======================================================================================================
# This is a script for generating FigureS2: Junctions coverage across whole blood samples
# #
# input:
#       1. FigureS2.in.RData
#          Data generated by running Figure_S2_getdata.R
#
# output:
#       1. FigureS2A.pdf, FigureS2B.pdf, FigureS2.pdf
#       2. FigureS2.out.RData
#          Store all data used and generated by running this script
#
# Note that the final figure was generated by using inkscape by combining figures from this script for visualization purposes
#
# =======================================================================================================



#!/bin/R

# look at the number of reads covering junctions for genes of interest

# Master directory
dir = Sys.getenv('RARE_DIS_DIR')


# load required functions
source('Figures_source.R')



#  Load input data
load(file = paste(dir,"/data/FigureS2.in.RData",sep=""))



#--- Libraries

library(cowplot)
library(ggplot2)
library(RColorBrewer)


fsize=15
RD_theme=theme_classic()+
	theme(axis.text.x= element_text(size=fsize),
	axis.text.y= element_text(size=fsize), 
	axis.title = element_text(size = fsize), 
    legend.text = element_text(size = fsize-1), 
    legend.title = element_text(size = fsize), 
    axis.ticks = element_line(size = 0.5),
	strip.background=element_blank(),
	panel.grid.major=element_blank(),
	panel.grid.minor=element_blank(),
	axis.text=element_text(size=fsize),
	panel.border=element_blank()) 


# Panel A
junction_coverage_density_plot=ggplot(nb_junction_cov, aes(x=percent_covered))+geom_density(fill="gray")+
	geom_vline(aes(xintercept=mean(percent_covered)), color="blue",linetype="dashed")+
	geom_vline(aes(xintercept=median(percent_covered)), color="red",linetype="dashed")+
	labs(x="Proportion of annotated junctions covered per gene", y="Density")+
	RD_theme

ggsave('FigureS2A.pdf', junction_coverage_density_plot, path=paste(dir,"/analysis/manuscript/figures/", sep=""), width=6, height=6)

# Panel B
disease_colors=brewer.pal(12,"Paired")
col_juncplot=c(grey.colors(n=11,start = 0.6, end = 1)[1:3],disease_colors[10])

disease_junc_plot=ggplot(disease_junc.m, aes(x=variable, y=value, fill=variable))+ 
	geom_bar(stat="identity")+ 
	scale_fill_manual(values=col_juncplot)+
	labs(x="", y="% Genes for which at least one junction\ncovered with at least 5 reads in 20% samples")+
	RD_theme+
	coord_flip()+ 
	theme(legend.position="")
disease_junc_plot
ggsave('FigureS2B.pdf', disease_junc_plot,path=paste(dir,"/analysis/manuscript/figures/", sep=""), width=7, height=6)


# Make combined plot
combined_plots=ggdraw()+draw_plot(junction_coverage_density_plot, 0,0,1/2,1)+
	draw_plot(disease_junc_plot, 1/2,0,1/2,1)+
	draw_plot_label(c('A', 'B'), c(0,1/2), c(1,1), size = 15)

#combined_plots
pdf(paste(dir,"/analysis/manuscript/figures/FigureS2.pdf",sep=""), w=8, h=6)
combined_plots
dev.off()

# Save data
save.image(file = paste(dir,"/data/FigureS2.out.RData",sep=""))
