# =======================================================================================================
# This is a script for generating FigureS9: Correction for batch effects - Splicing data
# #
# input:
#       1. FigureS9.in.RData
#          Data generated by running FigureS9_getdata.R
#
# output:
#       1. FigureS9A.pdf, FigureS9B.pdf, FigureS9C.pdf, FigureS9.pdf
#       2. FigureS9.out.RData
#          Store all data used and generated by running this script
#
# Note that the final figure was generated by using inkscape by combining figures from this script for visualization purposes
#
# =======================================================================================================




#!/bin/R
# Master directory
dir = Sys.getenv('RARE_DIS_DIR')


#  Load input data
load(file = paste(dir,"/data/FigureS9.in.RData",sep=""))


#Libraries
library(ggplot2)
library(cowplot)

# Panel A
pca_plot=autoplot(pca, scale=0, data=data_pca, colour="batch")   + scale_colour_brewer(palette="Set3") + xlim(-10,10) + ylim(-5, 20) +theme(legend.position="")
ggsave('FigureS9A.pdf', pca_plot, path=paste(dir,"/analysis/manuscript/figures/", sep=""), width=6, height=6)

# Panel B
pca_corrected_plot=autoplot(pca_regressed, scale=0, data=data_pca, colour="batch")   + scale_colour_brewer(palette="Set3")+ xlim(-10,10) + ylim(-5, 20)+theme(legend.position="")
ggsave('FigureS9B.pdf', pca_plot, path=paste(dir,"/analysis/manuscript/figures/", sep=""), width=6, height=6)

# Panel C
cor.heatmap=ggplot(data = cor.pc.cov.m, aes(x=Var2, y=as.factor(Var1), fill=value)) + 
  geom_tile(color = "white")+
 scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
   midpoint = 0, limit = c(-1,1), space = "Lab", 
   name="Pearson\nCorrelation") +
  theme_minimal()+ 
  coord_fixed() + labs(x='PCs', y='Covariates')+theme(legend.position="right")+ theme(axis.text.x = element_text(angle = 45, hjust = .8))

ggsave('FigureS9C.pdf', cor.heatmap, path=paste(dir,"/analysis/manuscript/figures/", sep=""), width=6, height=6)


## combined_plot
sup_pca_plot=ggdraw()+draw_plot(pca_plot, 0,1/2,1/2,1/2)+
	draw_plot(pca_corrected_plot, 1/2,1/2,1/2,1/2)+
	draw_plot(cor.heatmap, 0,0,1/2,1/2)+
	draw_plot_label(c('A', 'B', 'C'), c(0,1/2, 0), c(1,1,1/2), size = 15)


pdf(paste(dir,"/analysis/manuscript/figures/FigureS9.pdf",sep=""), w=8, h=8)
sup_pca_plot
dev.off()

# Save data
save.image(file = paste(dir,"/data/FigureS9.out.RData",sep=""))

